name = "rss-cloudflare"
main = "src/index.ts"
compatibility_date = "2025-06-23"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间配置
kv_namespaces = [
  { binding = "RSS_FEEDS", id = "kv-id" }
]

# R2 存储桶配置
[[r2_buckets]]
binding = 'RSS_BUCKET'
bucket_name = 'rss-data'

# 环境变量配置
[vars]
GITHUB_CLIENT_ID = "github-cl"
GITHUB_CLIENT_SECRET = "github-se"
ALLOWED_GITHUB_USERS = "allow-user-name"
APP_URL = "deploy-url"

# 静态资源配置
[site]
bucket = "./public" 
